baseurl = "https://digitaldrummerj.me"
title = "Justin James"
Copyright = "Copyright 2015-2022.  All content is the property of Justin James and digitaldrummerj.me."

buildDrafts = true
buildFuture = true

canonifyurls = false
paginate = 10
theme = "bootstrap"
languageCode = "en"

#googleAnalytics = "" # delete or comment to disable Google Analytics JS generation

# Set to true to enable syntax highlighting in code fences with a language tag
pygmentsCodefences =  true

# color-codes for highlighting derived from this style
pygmentsStyle = "manni" #"friendly"

[Author]
  name = "Justin James"


[params]
  copyright = "Created with â™¥ by <a href='/about/'>Justin James</a>. All content is the property of Justin James and digitaldrummerj.me. This blog, its content, and opinions are my own."
  DateForm = "January 2, 2006"
  Description = "Web Developer, Tester, and Professional Speaker"
  DescriptionMeta = "Web Developer, Tester and Professional Speaker; passionate about good code, automated testing, devops, and presenting."
  Headshot = "/images/profile-image-display.png"
  postSummariesFrontPage = 5
  showReadTime = false
  customCSS = ["/css/custom.css"] # custom CSS
  defaultHeaderImage = "/images/bg.png"
  safariMaskColor = "#545271"
  msApplicationTileColor = "#545271"
  Comments = false
  mainSections = ["posts"]

# Allow HTML to be included from Markdown files
[markup.goldmark.renderer]
  unsafe = true

# Used in the theme\layouts\contact\single.html
[params.contactusform]
  formSpreeUrl = "https://formspree.io/f/xjvjjevz"
  thankyouPage = "/thankyou/"

# Used to define the twitter card site
[Social]
  twitter = "digitaldrummerj"

[[params.social]]
  title = "linkedin"
  url = "https://www.linkedin.com/in/digitaldrummerj/"
[[params.social]]
  title = "github"
  url = "https://github.com/digitaldrummerj"
[[params.social]]
  title = "envelope"
  url = "/contact/"
[[params.social]]
  title = "twitter"
  url = "https://twitter.com/digitaldrummerj"

[[menu.main]]
  name ="Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2
[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 3
[[menu.main]]
  name = "Speaking"
  url = "/speaking"
  weight = 4
[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 5
[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 6

[taxonomies]
  series = "series"
  category = "categories"

[permalinks]
  blog = "/:filename/"
  page = "/:slug/"
  posts = "/:filename/"

  [params.sharingicons]
    # Hide the sharing icons on posts? (Default: false)
    hide = false

    # Optionally, set any of these to false to hide them:
    facebook = true
    linkedin = true
    twitter = true

[outputs]
home = ["HTML","RSS", "FEED","Lunr"]

[outputFormats.Lunr]
baseName = "lunr"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.lunr]
vars = ["title", "summary", "content", "description", "publishdate", "uri", "categories"]
params = ["categories"]

[mediaTypes]
[mediaTypes."application/rss"]
suffixes = ["xml"]

[outputFormats]
[outputFormats.FEED]
mediatype = "application/rss"
baseName = "feed"
