# Your project's server will run on localhost:xxxx at this port
PORT: 1313

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# Foundation source directories.
PATHS:
  prodconfig: "../../../config-prod.toml"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "../source/scss"
  # Paths to JavaScript libraries, which are combined into one file
  javascript:
    # Libraries required by Foundation
    # Files in `/source`
    - "../source/js/app.js"
    - "../source/js/!(app).js"
